In [3]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

In [4]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
data = pd.DataFrame(data)

In [5]:
scaler = MinMaxScaler()
scaler = scaler.fit(data)

In [8]:
result = scaler.transform(data)

In [9]:
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [12]:
result = scaler.fit_transform(data)

In [13]:
scaler.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [14]:
scaler = MinMaxScaler(feature_range=[5, 10])
scaler.fit_transform(data)

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [19]:
data.min(axis=0).tolist()

[-1.0, 2.0]

In [20]:
X = data.copy()
X_nor = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_nor

0     1
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  1.00  1.00

In [21]:
X_returned = X_nor * (X.max(axis=0) - X.min(axis=0)) + X.min(axis=0)

In [22]:
X_returned

0     1
0 -1.0   2.0
1 -0.5   6.0
2  0.0  10.0
3  1.0  18.0